# Generated by Django 5.2.1 on 2025-05-11 16:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAPICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, unique=True)),
                ('response', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WBAPIStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('last_response_time', models.FloatField(blank=True, null=True)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Statistics',
                'verbose_name_plural': 'API Statistics',
            },
        ),
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, unique=True, verbose_name='API Endpoint')),
                ('response', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Response Data')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'API Cache',
                'verbose_name_plural': 'API Caches',
                'ordering': ['-expires_at'],
                'indexes': [models.Index(fields=['endpoint'], name='wb_api_apic_endpoin_855f98_idx'), models.Index(fields=['expires_at'], name='wb_api_apic_expires_cd436c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'WB Product',
                'verbose_name_plural': 'WB Products',
                'indexes': [models.Index(fields=['product_id'], name='wb_api_wbpr_product_89e851_idx'), models.Index(fields=['price'], name='wb_api_wbpr_price_2e2170_idx'), models.Index(fields=['category'], name='wb_api_wbpr_categor_811b86_idx')],
            },
        ),
    ]
