# Generated by Django 5.2.1 on 2025-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicache',
            options={},
        ),
        migrations.RenameIndex(
            model_name='apicache',
            new_name='api_cache_endpoin_204034_idx',
            old_name='wb_api_apic_endpoin_855f98_idx',
        ),
        migrations.RenameIndex(
            model_name='apicache',
            new_name='api_cache_expires_693ada_idx',
            old_name='wb_api_apic_expires_cd436c_idx',
        ),
        migrations.RemoveField(
            model_name='apicache',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='apicache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apicache',
            name='endpoint',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apicache',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apicache',
            name='response',
            field=models.JSONField(),
        ),
        migrations.AlterModelTable(
            name='apicache',
            table='api_cache',
        ),
    ]
